targets:
  debian-7: &debian
    dependencies:
      - gvfs-bin
      - gvfs-fuse
  debian-8:
    <<: *debian
  ubuntu-14.04:
    <<: *debian
  ubuntu-12.04:
    <<: *debian
  centos-6: &el
    dependencies:
      - gvfs
      - gvfs-fuse
  centos-7:
    <<: *el
before:
  - mv support/packager/Procfile .
  - mv support/packager/.godir .
