language: go
sudo: true
services:
  - docker
addons:
  apt:
    packages:
      - upx-ucl
go:
  - 1.8
  - tip

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

install:
  - make deps

script:
  - make lint
  - make build
  - make test
  - ./docker-volume-gvfs

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make compress
  - docker --version
  - make docker-plugin
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - make docker-plugin-push

deploy:
  provider: releases
  api_key:
    secure: Mn5jPnIosAJeRD6WDbQBkwIlI7zShQd7bxrs0t0/dVxTTI/vOjAQ/n2UtMWBEc/zvc7s1mmdbtTW2UlcI8r+LFig/gp/Fsd9Cyfap45hOtG0660ockIwMJEBSJemnT5Z4UuY4tGlMtM9CH7K316VtAdHNVBka4+wnTPoNhv6SQMYjffajhRRLlNgrDFkjdJ8A/E5GfCfov0bX++GqjS6QKVTBnUwLfSIt48xXOJIgfpgLZPos3NaiBG/vGjsLlrhDb8YPnbe/ITO/1ZymBbY4sEn2WAeflXG5wGYUGnPCE3ix2VwC6PnfWEqJDW7ZzpHnAUBu+V/f/S+b3r2O50vLcPuQR8zxxs//ei/RRoIRvMiTycFZ9uFTOC/VLja8dpvl40ZYknU5NINfRZdwG1CkCORMPNOgUW5+bYrh6HygteE9z77mYQZYlgrQ07os0IIq1cnkWtVOFDCJOL1SnHUxfquPCsaC+0u33w/r+iqfNn3gPA7q94xtY2lUSLFizvSeKcyPwsHuhskomR++pRcn9djZskDTByyeeIptpBc3kqZfqpvRAM7HiIgvCbncFPLEx+IKjCJf3zOlx1cES4qUmWZH4T5k+G0soIWD2mJB4xY5RKQfJC1OnrkIxzIv1HhQD/0UjDA+Vhpq6mB2grdvEAAWdCN+1C0hbpgJIxO1k8=
  file: "./docker-volume-gvfs"
  skip_cleanup: true
  on:
    tags: true
