language: go
sudo: false
go:
 - 1.6
 - 1.7
 - tip
install:
 - go get github.com/golang/lint/golint
script:
 - go vet ./... || echo "Something could be improved !"
 - test -z "$(golint ./... | grep -v vendor/ | tee /dev/stderr)"
 - test -z "$(gofmt -s -l . | grep -v vendor/ | tee /dev/stderr)"
 - go list ./... | go test -v
 - make
 - ./docker-volume-gvfs
